import { Connection, Keypair, LAMPORTS_PER_SOL } from '@solana/web3.js';
import nacl from 'tweetnacl';
import { ShieldPool } from '../sdk/src/pool';
import { SOL_MINT } from '../sdk/src/utxo';
const connection = new Connection('http://127.0.0.1:8899', 'confirmed');
const kp = Keypair.generate();
const P = await ShieldPool.init({ connection, relayerUrl: process.env.RELAYER_URL ?? 'http://127.0.0.1:8787', artifacts: { wasm: new URL('../circuits/transaction2.wasm', import.meta.url).pathname, zkey: new URL('../circuits/transaction2.zkey', import.meta.url).pathname } });
await P.unlock(kp.publicKey, async (m) => nacl.sign.detached(m, kp.secretKey));
const tx = await P.buildDepositTx(SOL_MINT, BigInt(LAMPORTS_PER_SOL), kp.publicKey);
const msg = tx.message;
console.log('version', tx.version, 'static accounts', msg.staticAccountKeys.length, 'alt lookups', msg.addressTableLookups.length);
for (const ix of msg.compiledInstructions) console.log('ix program', msg.staticAccountKeys[ix.programIdIndex].toBase58().slice(0, 8), 'accounts', ix.accountKeyIndexes.length, 'data', ix.data.length);
console.log('serialized', tx.serialize().length);
