[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shieldpool = "7Bts9gjMRYG577hbipnAZMuEiBWnGy4SwkqN8TjRpuVF"

[programs.devnet]
shieldpool = "7Bts9gjMRYG577hbipnAZMuEiBWnGy4SwkqN8TjRpuVF"

[programs.mainnet]
shieldpool = "7Bts9gjMRYG577hbipnAZMuEiBWnGy4SwkqN8TjRpuVF"

[provider]
cluster = "localnet"
wallet = "../../keys/pool/deployer.json"
